apiVersion: v1
kind: Service
metadata:
  name: vault-backend
  namespace: {{ .Values.nginx.namespace }}
spec:
  selector:
    app: vault-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
